### ISSUE TITLE
PMID: 35293864 summary

### ISSUE THREAD

**Issue by manulera** [manulera/discussions_curation#2]
# PMID: 35293864

Microtubule rescue at midzone edges promotes overlap stability and prevents spindle collapse during anaphase B

### Fig. 1 and supps

* Microtubule growth speed decreases with anaphase progression.
* Microtubule rescues occur at midzone edges.

### Fig. 2 and supps
Deletion of several genes does not prevent microtubule growth speed decrease during anaphase, although they may affect the actual speed.

| Genotype      | Phenotype |Figure|
| ----------- | ----------- |---|
| cls1 overexp      | reduced growth speed during anaphase       |Fig. 2 supp 2F|
| cls1 shutdown   | increased growth speed during anaphase        |Fig. 2 supp 2E|
| mal3D   | reduced growth speed during anaphase        |Fig. 2H|
| klp5Dklp6D   | increase duration of mt growth event / reduced catastrophe       |Fig. 2 supp 1|

### Fig. 3 and supps

* The decrease in microtubule growth happens when the nuclear membrane bridge wraps around the spindle at dumbbell transition.

| Genotype      | Phenotype |Figure|
| ----------- | ----------- |---|
| Klp9OE overexp      | Longer cells / faster spindle elongation anaphase B       | Fig. 3 supp 1 A, C
| cdc25-22   | Longer cells / faster spindle elongation anaphase B| Fig. 3 supp 1 A, C

These were already published in Kruger et al. 2019, so I guess they should be included when that paper is added. Except longer cells in Klp9OE, son include that one.

https://pubmed.ncbi.nlm.nih.gov/30806623/

### Fig. 4 and supps
* Preventing the dumbbell transition using cerulenin or ark1-as3 prevents the decrease in MT growth speed at late anaphase (ark1-as3 membrane phenotype not included since this is just a consequence of a failure of chromosome segregation during anaphase A, and this is well documented). Deleting les1 and nem1 reduces the decrease in microtubule growth.

| Genotype      | Phenotype |Figure|
| ----------- | ----------- |---|
| les1D       | Faster MT growth in nuclear membrane bridge| Fig. 4 supp 2
| nem1D   | Faster MT growth in nuclear membrane bridge| Fig. 4 supp 2

### Fig. 5 and supps

* Deleting ase1 leads to the loss of the organisation of rescues. This is because Ase1 recruits the rescue factor Cls1/Peg1 to the midzone.
* This in turn leads to shorter spindles at the end of anaphase and spindle collapse in cells (this was reported before in Yamashita et al. 2005, PMID:15509653).
* We also alter ase1 expression levels and find:
	* Ase1 overexpression reduces spindle elongation speed (previously reported in Rincon et al. 2017)
	* Ase1 knockdown increases growth speed throughout anaphase

| Genotype      | Phenotype |Figure|
| ----------- | ----------- |---|
|ase1D| Loss of microtubule rescue organisation| Fig. 5E
|ase1D| Faster MT growth in nuclear membrane bridge | Fig. 5F,G
| ase1 shutdown   | increased growth speed during anaphase        |Fig. 5 supp 3E|

## TODO list:

- [x] Add annotations from this paper
- [x] Check annotations from previous papers:
    - [x] Kruger et al.
        - cdc25 and klp9OE, also cell size of klp9OE? probably not included
    - [x] Yamashita et al. 2005
        - Reduced spindle length at anaphase end and anaphase onset
        - Spindle collapse
        - What about spindle collapse severity / penetrance?
    - [x] Bratman and Chang
        - Cls1 interaction and so.
        - Annotation of peg1 to bundle formation, very indirect. Should be microtubule rescue instead.
        -

**Comment by manulera** [comment]
Closed but, continues in https://github.com/pombase/curation/issues/3259
