### ISSUE TITLE
PMID:24239120

### ISSUE THREAD

**Issue by manulera** [manulera/discussions_curation#5]
# PMID:24239120

Antagonistic Spindle Motors and MAPs Regulate Metaphase Spindle Length and Chromosome Segregation

Metaphase describes a phase of mitosis where chromosomes are attached and oriented on the bipolar spindle for subsequent segregation at anaphase. In diverse cell types, the metaphase spindle is maintained at characteristic constant length [1-3]. Metaphase spindle length is proposed to be regulated by a balance of pushing and pulling forces generated by distinct sets of spindle microtubules (MTs) and their interactions with motors and MT-associated proteins (MAPs). Spindle length is further proposed to be important for chromosome segregation fidelity, as cells with shorter- or longer-than-normal metaphase spindles, generated through deletion or inhibition of individual mitotic motors or MAPs, showed chromosome segregation defects. To test the force-balance model of spindle length control and its effect on chromosome segregation, we applied fast microfluidic temperature control with live-cell imaging to monitor the effect of deleting or switching off different combinations of antagonistic force contributors in the fission yeast metaphase spindle. We show that the spindle midzone proteins kinesin-5 cut7p and MT bundler ase1p contribute to outward-pushing forces and that the spindle kinetochore proteins kinesin-8 klp5/6p and dam1p contribute to inward-pulling forces. Removing these proteins individually led to aberrant metaphase spindle length and chromosome segregation defects. Removing these proteins in antagonistic combination rescued the defective spindle length and in some combinations also partially rescued chromosome segregation defects.

## Revise from intro

- [x] cut7 rescue

### Figure 1

* [x] Longer spindle:
  - [x] klp5
  - [x] klp6
  - [x] dam1 -> severity low
* [x] Shorter spindle:
  - [x] pkl1 -> severity low
  - [x] ase1

* [x] Normal spindle:
  - [x] klp2
  - [x] klp3
  - [x] tea2
  - [x] klp8
  - [x] klp9
  - [x] dhc1

### Figure S1

* [x] Increased spindle elongation speed during phase I (prophase)
  - [x] klp6
* [x] Reduced spindle elongation speed during phase I (prophase)
  - [x] ase1
* [x] Increased time before anaphase (increased duration of Phase I and II combined)
  - [x] klp5
  - [x] klp6
  - [x] ase1
  - [x] dam1 -> severity high

* [x] Rescued duration
  - [x] klp5 mad2
  - [x] dam1 mad2

* [x] Partial rescue of metaphase length
  * [x] klp5 mad2

### Figure 2

* [x] Total rescue of metaphase length
  * [x] klp5 ase1
  * [x] dam1 ase1
  * [x] ~~cut7-24 klp6~~
  * [x] **(check Phong)
  * [x]~~ cut7-24 dam1~~
  * [x] **(check Phong)

* [x] Rescued duration
  - [x] dam1 ase1

* [x] In the text only
  * [x] Check Synthetic lethality dam1 klp5(ref 33)
  * [x] Very sick-> dam1A8 klp5 (ref 33)

* [x] Spindle collapse after normal metaphase spindle formation (Fig. 2A-C). There may be an instance where shifting to the restrictive temperature would not cause collapse, this experiment shows that cut7 is not only required to stablish bipolarity, but also to maintain it.
  * [x] cut7.24
* [x] No spindle collapse (after normal metaphase spindle formation)??
  * [x] ~~cut7.24 klp6~~
  * [x]  **(check Phong)
  * [x] ~~cut7.24 dam1~~
  * [x] **(check Phong)

### Figure 3

* [x] Lagging chromosome (is it really lagging chromosome or is it just delayed?). Specially considering ase1 rescues:
  * [x] klp5 (40%)
  * [x] klp6 (~40%)
  * [x] dam1 (~20%)
* [x] Chromosome missegregation
  * [x] klp6 (~10%)
  * [x] dam1 (~20%)
* [x] Partial rescue of lagging chromosome:
  * [x] klp5 ase1 (90%)
  * [x] ~~klp6 cut7-24~~
  * [x] **(check Phong) (~10%)
* [x] Worse chromosome missegregation:
  * [x] ~~dam1 cut7-24~~
  * [x] **(check Phong) (~55%)

### Figure 4

* [x] Transient abrupt spindle length decrease at anaphase onset.
  * [x] klp5 ase1
  * [x] klp6 cut7-24

## Discuss with Val

* [x] cut7-24-GFP is not lethal at 37C (Fig. S2A)
* [x] Discuss lagging chromosome or delayed start with Val
* [x] Worth adding normal spindle length at metaphase for single deletions?
* [x] Special phenotype of collapse half-way. Likely if it matters it will be mentioned again.
* [x] Do we add conditions (temperature) to genetic interactions?
* [x] Lagging chromosome phenotype
* [x] Are genetic interactions directional?
* [x] Canto
  * [x] Annotate multiple alles in canto at the same time?
  ![Screenshot 2022-04-22 at 17 00 03](https://user-images.githubusercontent.com/22526102/164753007-892d5516-5fc3-49f7-9f75-5f2c173708ee.png)

## TODO

* [x] If cut7ts mutants are kept, add the condition of high temperature

## Ask Phong

* [x] Is cut7ts rescued by klp6 and dam1? or just if you switch mid-way?
  * Just switch mid-way
* [x] Remove cut7ts conditions

## Go terms

* [x] Create and discuss ticket in GO for spindle
* [x] Pending discussion with Val on regulation in GO

**Comment by manulera** [comment]
## Ontology changes to be requested: 

Rearrange the children of FYPO:0000131
Revise FRYPO:4309
Why are FYPO:0000324 and FYPO:0000324 not siblings?
Add bipolar mitotic spindle, could be a child of FYPO:0001399
Transient abrupt spindle length decrease at anaphase onset (New term)


* [x] (make a ticket)
